
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 your_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    env_file:
      - .env
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:

networks:
  app_network:
    driver: bridge